apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: linode2.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  annotations:
    "helm.sh/resource-policy": keep
  name: storagebuckets.object.linode.kubeform.com
spec:
  group: object.linode.kubeform.com
  names:
    kind: StorageBucket
    listKind: StorageBucketList
    plural: storagebuckets
    singular: storagebucket
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeformOutput:
                properties:
                  accessKey:
                    type: string
                  acl:
                    type: string
                  cert:
                    type: object
                  cluster:
                    type: string
                  corsEnabled:
                    type: boolean
                  id:
                    type: string
                  label:
                    type: string
                  lifecycleRule:
                    items:
                      properties:
                        ID:
                          type: string
                        abortIncompleteMultipartUploadDays:
                          format: int64
                          type: integer
                        enabled:
                          type: boolean
                        expiration:
                          properties:
                            date:
                              type: string
                            days:
                              format: int64
                              type: integer
                            expiredObjectDeleteMarker:
                              type: boolean
                          type: object
                        noncurrentVersionExpiration:
                          properties:
                            days:
                              format: int64
                              type: integer
                          required:
                          - days
                          type: object
                        prefix:
                          type: string
                      required:
                      - enabled
                      type: object
                    type: array
                  secretKey:
                    type: string
                  versioning:
                    type: boolean
                required:
                - cluster
                - label
                type: object
              providerRef:
                properties:
                  name:
                    type: string
                type: object
              resource:
                properties:
                  accessKey:
                    type: string
                  acl:
                    type: string
                  cert:
                    type: object
                  cluster:
                    type: string
                  corsEnabled:
                    type: boolean
                  id:
                    type: string
                  label:
                    type: string
                  lifecycleRule:
                    items:
                      properties:
                        ID:
                          type: string
                        abortIncompleteMultipartUploadDays:
                          format: int64
                          type: integer
                        enabled:
                          type: boolean
                        expiration:
                          properties:
                            date:
                              type: string
                            days:
                              format: int64
                              type: integer
                            expiredObjectDeleteMarker:
                              type: boolean
                          type: object
                        noncurrentVersionExpiration:
                          properties:
                            days:
                              format: int64
                              type: integer
                          required:
                          - days
                          type: object
                        prefix:
                          type: string
                      required:
                      - enabled
                      type: object
                    type: array
                  secretKey:
                    type: string
                  versioning:
                    type: boolean
                required:
                - cluster
                - label
                type: object
              secretRef:
                properties:
                  name:
                    type: string
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                format: int64
                type: integer
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
